source 'https://rails-assets.org'
source 'https://rubygems.org'

gem 'bundler', '>= 1.8.4'

gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'ember-rails'
gem 'ember-source', '~> 1.9.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'test_squad'
end

source 'https://rails-assets.org' do
  gem 'rails-assets-jquery'

  group :development, :test do
    gem 'rails-assets-qunit'
    gem 'rails-assets-ember-qunit'
  end
end

