source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails', '4.2.0'
gem 'rails-api'
gem 'puma'
gem 'pg'

group :development, :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
  gem 'capybara'
end
