source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'pg'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'active_model_serializers', '0.9.3'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

