source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'rails-api'
gem 'spring', :group => :development
gem 'pg'
gem 'warden'
gem 'bcrypt'

group :development, :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
end
