development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>


test:
  secret_key_base: ff3ba46a4b77d499e1ce69f314748005194e6022dd014102b4a9b4004b28282e3d363c1b8bbc5a28a84ba9c0113be5ba32b90a953b8aaa3e8a908048f479bcc

