source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# gems added during the treehouse tutorials
gem 'bootstrap-sass', '~> 3.2.0.2'
gem 'devise', '~> 3.4.0'
gem 'simple_form', '>= 3.1.0.rc2'
gem 'state_machine', :git => 'https://github.com/seuros/state_machine.git'
gem 'draper', '~> 1.4.0'
gem 'js-routes', '~> 0.9.9'
gem 'paperclip', '>=3'
#added this for breadcrumbs helper instead of twitter-bootstrap-rails
gem 'bootstrap-sass-extras', '~> 0.0.2'
gem 'will_paginate', '~> 3.0'
gem 'bootstrap-will_paginate'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'faker'
  gem 'factory_girl_rails'
  gem 'capybara'
end

#heroku required gems
gem 'pg', '~> 0.11'
gem 'unicorn', '~> 4.8.3'
group :production, :staging do
  gem 'rails_12factor', '~> 0.0.3'
end

# other gems added after the tutorials
gem 'high_voltage', '~> 2.2.1'
gem 'rack-attack', '~> 4.2.0'
gem 'redcarpet', '~> 3.2.2'
gem 'pygments.rb', '~> 0.6.2'
gem 'haml-rails', '~> 0.9.0'
