# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e18af01d2b9f15dbea129014bee4bac27972f6b63eeb119d4956a04f3994b01e4edbfeb8eff8b384717ee9d4044199ce263ef9f18c042954be673f698a7d95e0

test:
  secret_key_base: 069b8a167e33a337baade4cbe7b6c526a2a6bebc33f8ffb93baa7a6a60e01d83cf65f3f7baac1cc95f0a555589c82e33a6007fb1ec8ee4cff1db7d94081c804a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
